DROP TABLE BSST_DU_GUID;

CREATE TABLE BSST_DU_GUID (
	DU_N_TICKET_ID 		INTEGER UNSIGNED NOT NULL,
	DU_N_LOCATION_ID	INTEGER UNSIGNED NOT NULL,
	DU_S_GUID			VARCHAR(256) NOT NULL,
	PRIMARY KEY(DU_S_GUID)
);
